/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Matias
 */
public class MainMenu_Form extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu_Form
     */
    public MainMenu_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmIngresarCarrera = new javax.swing.JMenuItem();
        jmEliminarCarrera = new javax.swing.JMenuItem();
        jmActualizarCarrera = new javax.swing.JMenuItem();
        jmListarCarrera = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenu3.setText("Carrera");

        jmIngresarCarrera.setText("Ingresar");
        jmIngresarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIngresarCarreraActionPerformed(evt);
            }
        });
        jMenu3.add(jmIngresarCarrera);

        jmEliminarCarrera.setText("Eliminar");
        jmEliminarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarCarreraActionPerformed(evt);
            }
        });
        jMenu3.add(jmEliminarCarrera);

        jmActualizarCarrera.setText("Actualizar");
        jmActualizarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActualizarCarreraActionPerformed(evt);
            }
        });
        jMenu3.add(jmActualizarCarrera);

        jmListarCarrera.setText("Listar");
        jmListarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarCarreraActionPerformed(evt);
            }
        });
        jMenu3.add(jmListarCarrera);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jmSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmIngresarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIngresarCarreraActionPerformed
        
        Form_IngresarCarrera fic = new Form_IngresarCarrera();
        
        fic.setVisible(true);
        
    }//GEN-LAST:event_jmIngresarCarreraActionPerformed

    private void jmEliminarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarCarreraActionPerformed
        
        Form_EliminarCarrera fec = new Form_EliminarCarrera();
        
        fec.setVisible(true);
    }//GEN-LAST:event_jmEliminarCarreraActionPerformed

    private void jmActualizarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActualizarCarreraActionPerformed
        Form_actualizarCarrera fac = new Form_actualizarCarrera();
        
        fac.setVisible(true);
    }//GEN-LAST:event_jmActualizarCarreraActionPerformed

    private void jmListarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarCarreraActionPerformed
        Form_ListarCarrera flc = new Form_ListarCarrera();
        
        flc.setVisible(true);
    }//GEN-LAST:event_jmListarCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmActualizarCarrera;
    private javax.swing.JMenuItem jmEliminarCarrera;
    private javax.swing.JMenuItem jmIngresarCarrera;
    private javax.swing.JMenuItem jmListarCarrera;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
